# Mobile Terminal Overlay Configuration
# Place this file in your home directory or project root

session_name: claude

# Repos for quick switching (each gets its own tmux session)
repos:
  - label: "mobile-terminal"
    path: "/home/gcbbuilder/dev/mobile-terminal-overlay"
    session: "claude"
  - label: "geo-cv"
    path: "/home/gcbbuilder/dev/geo-cv"
    session: "claude"
    startup_command: "claude"

# Role prefixes (from CLAUDE.md discovery)
role_prefixes: []

# Per-device overrides (keyed by Tailscale hostname)
devices:
  titan2:  # Unihertz Titan 2 - TODO: update hostname when on Tailscale
    font_size: 12
    physical_kb: true

# UI settings
theme: dark
font_size: 13
scrollback: 5000
