# Mobile Terminal Overlay Configuration
# Place this file in your home directory or project root

session_name: claude

# Repos for quick switching (each gets its own tmux session)
repos:
  - label: "mobile-terminal"
    path: "/home/gcbbuilder/dev/mobile-terminal-overlay"
    session: "claude"
  - label: "geo-cv"
    path: "/home/gcbbuilder/dev/geo-cv"
    session: "claude"
    startup_command: "claude"

# Role prefixes (from CLAUDE.md discovery)
role_prefixes: []

# UI settings
theme: dark
font_size: 13
scrollback: 5000
